### ISSUE TITLE
Seems like animation aren't working anymore

### ISSUE THREAD

**Issue by JeromevDEV** [mittalsam98/react-portfolio#1]
Hi,
it seems like the animations aren't working anymore.

**Comment by mittalsam98** [comment]
Hey,Animations are working properly on mobile

**Comment by JeromevDEV** [comment]
Hi @mittalsam98 , on web view the animation aren't working. I'm using Chrome

**Comment by mittalsam98** [comment]
Hey @JeromevDEV, fixed the animations

**Comment by mittalsam98** [comment]
> Hi, it seems like the animations aren't working anymore.

Fixed and Pushed the changes
